// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2k6-V-7MYlkr5CL21Nr0X6QVe9RY864E',
    appId: '1:1086675787674:web:7b0a4433d5a428688da423',
    messagingSenderId: '1086675787674',
    projectId: 'clinic-63f96',
    authDomain: 'clinic-63f96.firebaseapp.com',
    storageBucket: 'clinic-63f96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCutwTdqoJ_FTppM9R_9Vl1xG7pgpLNebA',
    appId: '1:1086675787674:android:8b1b2d443d4bf18a8da423',
    messagingSenderId: '1086675787674',
    projectId: 'clinic-63f96',
    storageBucket: 'clinic-63f96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgtjDJRmbDVnGnlGgbcqqTjRRams018w',
    appId: '1:1086675787674:ios:6c7ff7989babf86e8da423',
    messagingSenderId: '1086675787674',
    projectId: 'clinic-63f96',
    storageBucket: 'clinic-63f96.appspot.com',
    iosClientId: '1086675787674-0tqt57rtdf73espavg3ncl7hksmuoqqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrgtjDJRmbDVnGnlGgbcqqTjRRams018w',
    appId: '1:1086675787674:ios:6c7ff7989babf86e8da423',
    messagingSenderId: '1086675787674',
    projectId: 'clinic-63f96',
    storageBucket: 'clinic-63f96.appspot.com',
    iosClientId: '1086675787674-0tqt57rtdf73espavg3ncl7hksmuoqqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.clinicApp',
  );
}
